language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements_test.txt
  - pip install coveralls
script:
  - coverage run -m pytest
after_success:
  - coveralls
